
CREATE DATABASE School9;

USE School9;


CREATE TABLE Student (
    ID INT IDENTITY(1,1) NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Address VARCHAR(100) NOT NULL,
    Email VARCHAR(75) NOT NULL,
    Class VARCHAR(5) NOT NULL,
    PRIMARY KEY (ID)
);
